server:
  port: 1234

spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
    name: user-service
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
#    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG