spring:
  application:
    name: zhucezhongxin
  profiles:
    active: standard

eureka:
  instance:
    prefer-ip-address: false
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 5
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: true
    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8762/eureka/


logging.level.com.netflix:
  eureka: OFF
  discovery: OFF

---
spring:
  profiles: rc1
server:
  port: 8761

eureka.instance.hostname: eureka1

---
spring:
  profiles: rc2
server:
  port: 8762

eureka.instance.hostname: eureka2

---
spring:
  profiles: standard
server:
  port: 8761
